server:
  servlet:
    context-path: /upms

# datasource2
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: space.zero.september.admin.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #mp2.3+ 全局表前缀 mp_
    #table-prefix: mp_
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
#    logic-delete-value: 4
#    logic-not-delete-value: 0
    #Sequence生成器
#    DB2KeyGenerator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
september:
  datasource:
    mysql:
      db01:
        url: jdbc:mysql://127.0.0.1:3306/september?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: One_123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000


#认证服务器地址
security:
  auth:
    # 负载均衡方式，使用服务名
    server: http://zero-auth:10020
  encode:
    key: '1234567887654321' #必须16位
  oauth2:
    client:
      client-id: app
      client-secret: app
    resource:
      token-info-uri: ${security.auth.server}/auth/oauth/check_token
  ignore:
    urls:
      - /**
      - /metadata/**
      - /swagger-resources/**
      - /swagger-ui.html
      - /*/v2/api-docs
      - /swagger/api-docs
      - /webjars/**
    clients:
      - test

swagger:
  title: September API
  license: Powered By zero
  licenseUrl: https://non-zero.space/
  terms-of-service-url: https://non-zero.space/
  contact:
    email: 123123@gmail.com
    url: https://non-zero.space/about.html
  authorization:
    name: pigX OAuth
    auth-regex: ^.*$
    authorization-scope-list:
      - scope: server
        description: server all
    token-url-list:
      - http://${GATEWAY-HOST:pigx-gateway}:${GATEWAY-PORT:9999}/auth/oauth/token