package space.zero.september.webservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-07-22T20:52:17.280+08:00
 * Generated source version: 3.3.2
 *
 */
@WebServiceClient(name = "DemoServiceImplService",
                  wsdlLocation = "file:/Users/shen/Project/open/september/zero-business/zero-webservice/src/main/java/space/zero/september/webservice/client/demo.wsdl",
                  targetNamespace = "http://service.webservice.september.zero.space")
public class DemoServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.webservice.september.zero.space", "DemoServiceImplService");
    public final static QName DemoServicePort = new QName("http://service.webservice.september.zero.space", "DemoServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/shen/Project/open/september/zero-business/zero-webservice/src/main/java/space/zero/september/webservice/client/demo.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DemoServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/Users/shen/Project/open/september/zero-business/zero-webservice/src/main/java/space/zero/september/webservice/client/demo.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DemoServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DemoServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DemoServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public DemoServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DemoServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DemoServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns DemoService
     */
    @WebEndpoint(name = "DemoServicePort")
    public DemoService getDemoServicePort() {
        return super.getPort(DemoServicePort, DemoService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DemoService
     */
    @WebEndpoint(name = "DemoServicePort")
    public DemoService getDemoServicePort(WebServiceFeature... features) {
        return super.getPort(DemoServicePort, DemoService.class, features);
    }

}
