
package space.zero.september.webservice.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-07-22T20:52:17.227+08:00
 * Generated source version: 3.3.2
 *
 */
public final class DemoService_DemoServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.webservice.september.zero.space", "DemoServiceImplService");

    private DemoService_DemoServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = DemoServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        DemoServiceImplService ss = new DemoServiceImplService(wsdlURL, SERVICE_NAME);
        DemoService port = ss.getDemoServicePort();

        {
        System.out.println("Invoking sayHello...");
        Person person = new Person();
        person.setLastName("ppp");
        person.setFirstName("fff");
        java.lang.String result = port.sayHello(person);
        System.out.println("sayHello.result=" + result);


        }

        System.exit(0);
    }

}
