server:
  servlet:
    context-path: /test

kafka:
  bootstrap-servers: 127.0.0.1:9092 #指定kafka server的地址，集群配多个，中间，逗号隔开
  producer:
    retries: 1
    batch-size: 10240
    linger: 1
    buffer-memory: 1024000
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
  consumer:
    group-id: default_consumer_group #群组ID
    enable-auto-commit: true
    auto-commit-interval: 1000
    session-timeout: 15000
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
